apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - credentials.yaml
  - monitoring.yaml
  - tailscale.yaml
  - metallb.yaml
  - cert-manager.yaml
  - namespaces.yaml
  - postgres.yaml
  - valkey.yaml
