apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
spec:
  valuesContent: |-
    kubeEtcd:
      enabled: true
      endpoints:
        - 172.30.0.4
        - 172.30.0.5
        - 172.30.0.6
      service:
        enabled: true
        port: 2381
        targetPort: 2381
