apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - tailscale.yaml
  - https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml
  - cluster-upgrade-plan.yaml
  - prom-etcd-config.yaml
