users:
  default:
    password: ~
    networks:
      - ip: 127.0.0.1
      - ip: ::1
    profile: default
    quota: default

  admin:
    password: ${CLICKHOUSE_ADMIN_PASSWORD}
    networks:
      - ip: '::/0'
    profile: default
    quota: default
    access_management: 1

  user:
    password: ${CLICKHOUSE_CLIENT_PASSWORD}
    networks:
      - ip: '::/0'
    profile: default
    quota: default

profiles:
  default:
    max_memory_usage: 10000000000
    use_uncompressed_cache: 0
    load_balancing: random

quotas:
  default:
    interval:
      duration: 3600
      queries: 0
      errors: 0
      result_rows: 0
      read_rows: 0
      execution_time: 0
