apiVersion: batch/v1
kind: Job
metadata:
  name: valkey-{{ .Values.name }}-init
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": {{ .Values.hooks.hookDeletePolicy }}
spec:
  backoffLimit: {{ .Values.hooks.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.hooks.ttlSecondsAfterFinished }}
  template:
    spec:
      serviceAccountName: valkey-{{ .Values.name }}-reconciler
      restartPolicy: {{ .Values.hooks.restartPolicy }}
      containers:
        - name: init
          image: {{ .Values.cluster.reconcilerImage }}
          args:
            - init
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.name }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MASTERS
              value: {{ .Values.cluster.masters }}
            - name: REPLICAS_PER_MASTER
              value: {{ .Values.cluster.replicasPerMaster }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secret }}
                  key: {{ .Values.credentials.dataKeys.adminPassword }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: valkey-{{ .Values.name }}-scale-up
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": {{ .Values.hooks.hookDeletePolicy }}
spec:
  backoffLimit: {{ .Values.hooks.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.hooks.ttlSecondsAfterFinished }}
  template:
    spec:
      serviceAccountName: valkey-{{ .Values.name }}-reconciler
      restartPolicy: {{ .Values.hooks.restartPolicy }}
      containers:
        - name: scale-up
          image: {{ .Values.cluster.reconcilerImage }}
          args:
            - scale-up
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.name }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MASTERS
              value: {{ .Values.cluster.masters }}
            - name: REPLICAS_PER_MASTER
              value: {{ .Values.cluster.replicasPerMaster }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secret }}
                  key: {{ .Values.credentials.dataKeys.adminPassword }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: valkey-{{ .Values.name }}-scale-down
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": {{ .Values.hooks.hookDeletePolicy }}
spec:
  backoffLimit: {{ .Values.hooks.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.hooks.ttlSecondsAfterFinished }}
  template:
    spec:
      serviceAccountName: valkey-{{ .Values.name }}-reconciler
      restartPolicy: {{ .Values.hooks.restartPolicy }}
      containers:
        - name: scale-down
          image: {{ .Values.cluster.reconcilerImage }}
          args:
            - scale-down
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.name }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MASTERS
              value: {{ .Values.cluster.masters }}
            - name: REPLICAS_PER_MASTER
              value: {{ .Values.cluster.replicasPerMaster }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secret }}
                  key: {{ .Values.credentials.dataKeys.adminPassword }}
