apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
resources:
  - main.yaml

configMapGenerator:
  - name: valkey-config
    files:
      - ../../valkey.conf
  - name: valkey-acl
    files:
      - ../../users.acl

generatorOptions:
  disableNameSuffixHash: true
