apiVersion: v1
kind: Namespace
metadata:
  name: ingress-controller

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: &name haproxy-ingress
  namespace: kube-system
spec:
  repo: https://haproxy-ingress.github.io/charts
  chart: *name
  version: 0.14.9
  targetNamespace: ingress-controller
  createNamespace: true
  # NOTE: if you want to change the ports, look into dual service cutover for zero downtime.
  # we want to let the helm chart manage the service so we don't have to worry about updates and breaking changes.
  # only when we're changing the ports (which should be once in a blue moon) will we then manually
  # manage the service so that we can do the dual service cutover, but then we'll change it back
  # https://github.com/haproxy-ingress/charts/blob/release-0.14/haproxy-ingress/values.yaml
  valuesContent: |-
    controller:
      ingressClassResource:
        enabled: true
      kind: DaemonSet
      service:
        httpPorts:
          - port: 80
            targetPort: http
            nodePort: 30080
        httpsPorts:
          - port: 443
            targetPort: https
            nodePort: 30443
      config:
        use-forwarded-headers: "true"
        forwarded-for-header: "X-Forwarded-For"
