apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: main
resources:
  - main.yaml

configMapGenerator:
  - name: clickhouse-config
    files:
      - ../../clickhouse/config.yaml
  - name: clickhouse-users
    files:
      - ../../clickhouse/users.yaml
  - name: clickhouse-keeper-config
    files:
      - ../../keeper/keeper.yaml

generatorOptions:
  disableNameSuffixHash: true
