apiVersion: v2
name: postgres
description: A Helm chart for PostgreSQL clusters with Patroni, PgDog, and PgBackRest
type: application
version: 0.1.0
appVersion: 18
keywords:
  - postgresql
  - patroni
  - pgdog
  - pgbackrest
  - database
maintainers:
  - name: pandoks
dependencies: []
