apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../apps
patches:
  - path: dev-patch.yaml
  - path: ../../packages/postgres/kube/main/dev-patch.yaml
  - path: ../../packages/valkey/kube/main/dev-patch.yaml
  - path: ../../packages/clickhouse/kube/main/dev-patch.yaml
