name: Build Images and Push
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/postgres/patroni/**'
      - 'packages/postgres/pgcat/**'
      - 'packages/postgres/pgbackrest/**'
      - 'packages/valkey/**'
      - 'packages/clickhouse/clickhouse/**'
      - 'packages/clickhouse/keeper/**'
      - 'packages/clickhouse/backup/**'
      # NOTE: you can exclude files/directories/subdirectories using `!` prefix (!packages/**)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    strategy:
      matrix:
        image:
          - name: patroni
            path: ./packages/postgres/patroni/Dockerfile
          - name: pgcat
            path: ./packages/postgres/pgcat/Dockerfile
          - name: pgbackrest
            path: ./packages/postgres/pgbackrest/Dockerfile
          - name: valkey
            path: ./packages/valkey/Dockerfile
          - name: valkey_reconciler
            path: ./packages/valkey/reconciler/Dockerfile
          - name: clickhouse
            path: ./packages/clickhouse/clickhouse/Dockerfile
          - name: clickhouse_keeper
            path: ./packages/clickhouse/keeper/Dockerfile
          - name: clickhouse_backup
            path: ./packages/clickhouse/backup/Dockerfile

    steps:
      - uses: actions/checkout@v4

      - id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            patroni:
              - 'packages/postgres/patroni/**'
            pgcat:
              - 'packages/postgres/pgcat/**'
            pgbackrest:
              - 'packages/postgres/pgbackrest/**'
            valkey:
              - 'packages/valkey/**'
            valkey_reconciler:
              - 'packages/valkey/reconciler/**'
            clickhouse:
              - 'packages/clickhouse/clickhouse/**'
            clickhouse_keeper:
              - 'packages/clickhouse/keeper/**'
            clickhouse_backup:
              - 'packages/clickhouse/backup/**'

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          # NOTE: github.repository includes the owner/org (ghcr.io/<owner/org>/repo-name)
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and Push
        if: github.event_name == 'workflow_dispatch' || steps.changes.outputs[matrix.image.name] == 'true'
        id: push
        uses: docker/build-push-action@v6
        with:
          context: . # WARN: all dockerfiles should have a context of the root of the repo
          file: ${{ matrix.image.path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate Attestation
        if: github.event_name == 'workflow_dispatch' || steps.changes.outputs[matrix.image.name] == 'true'
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
