name: Build and Publish
on:
  workflow_dispatch:
  create:
    branches:
      - '**'
  push:
    paths:
      - 'packages/postgres/**'
      - 'packages/valkey/**'
      - 'packages/argocd/**'
      - 'packages/clickhouse/**'
      # NOTE: you can exclude files/directories/subdirectories using `!` prefix (!packages/**)

jobs:
  build-publish-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    strategy:
      matrix:
        image:
          - name: patroni
            path: ./packages/postgres/patroni/Dockerfile
          - name: pgbackrest
            path: ./packages/postgres/pgbackrest/Dockerfile
          - name: valkey
            path: ./packages/valkey/Dockerfile
          - name: valkey-reconciler
            path: ./packages/valkey/reconciler/Dockerfile
          - name: argocd-sst-plugin
            path: ./packages/argocd/Dockerfile
          - name: clickhouse
            path: ./packages/clickhouse/clickhouse/Dockerfile
          - name: clickhouse-keeper
            path: ./packages/clickhouse/keeper/Dockerfile
          - name: clickhouse-backup
            path: ./packages/clickhouse/backup/Dockerfile

    steps:
      - uses: actions/checkout@v4

      - id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            patroni:
              - 'packages/postgres/patroni/**'
            pgbackrest:
              - 'packages/postgres/pgbackrest/**'
            valkey:
              - 'packages/valkey/**'
            valkey-reconciler:
              - 'packages/valkey/reconciler/**'
            argocd-sst-plugin:
              - 'packages/argocd/**'
            clickhouse:
              - 'packages/clickhouse/clickhouse/**'
            clickhouse-keeper:
              - 'packages/clickhouse/keeper/**'
            clickhouse-backup:
              - 'packages/clickhouse/backup/**'

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          # NOTE: github.repository includes the owner/org (ghcr.io/<owner/org>/repo-name)
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and Push
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'create' || steps.changes.outputs[matrix.image.name] == 'true'
        id: push
        uses: docker/build-push-action@v6
        with:
          context: . # WARN: all dockerfiles should have a context of the root of the repo
          file: ${{ matrix.image.path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate Attestation
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'create' || steps.changes.outputs[matrix.image.name] == 'true'
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: false

  publish-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        chart:
          - name: postgres
            path: ./packages/postgres/chart
          - name: valkey
            path: ./packages/valkey/chart
          - name: clickhouse
            path: ./packages/clickhouse/chart

    steps:
      - uses: actions/checkout@v4

      - id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            postgres:
              - 'packages/postgres/chart/**'
            valkey:
              - 'packages/valkey/chart/**'
            clickhouse:
              - 'packages/clickhouse/chart/**'

      - name: Install Helm
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'create' || steps.changes.outputs[matrix.chart.name] == 'true'
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Login to GHCR
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'create' || steps.changes.outputs[matrix.chart.name] == 'true'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and Push Helm Chart
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'create' || steps.changes.outputs[matrix.chart.name] == 'true'
        run: |
          helm package ${{ matrix.chart.path }}
          LOWERCASE_REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          helm push ${{ matrix.chart.name }}-*.tgz oci://ghcr.io/${LOWERCASE_REPO_OWNER}/charts
