name: Publish Helm Chart
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/postgres/chart/**'
      - 'packages/valkey/chart/**'
      - 'packages/clickhouse/chart/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        chart:
          - name: postgres
            path: ./packages/postgres/chart
          - name: valkey
            path: ./packages/valkey/chart
          - name: clickhouse
            path: ./packages/clickhouse/chart

    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and Push Helm Chart
        run: |
          helm package ${{ matrix.chart.path }}
          LOWERCASE_REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          helm push ${{ matrix.chart.name }}-*.tgz oci://ghcr.io/${LOWERCASE_REPO_OWNER}/charts
