name: Publish Helm Chart
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/postgres/chart/**'
      - 'packages/valkey/chart/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        chart:
          - name: postgres
            path: ./packages/postgres/chart
          - name: valkey
            path: ./packages/valkey/chart

    steps:
      - uses: actions/checkout@v4

      - id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            postgres:
              - 'packages/postgres/chart/**'
            valkey:
              - 'packages/valkey/chart/**'
            clickhouse:
              - 'packages/clickhouse/chart/**'

      - name: Install Helm
        if: github.event_name == 'workflow_dispatch' || steps.changes.outputs[matrix.chart.name] == 'true'
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Login to GHCR
        if: github.event_name == 'workflow_dispatch' || steps.changes.outputs[matrix.chart.name] == 'true'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and Push Helm Chart
        if: github.event_name == 'workflow_dispatch' || steps.changes.outputs[matrix.chart.name] == 'true'
        run: |
          helm package ${{ matrix.chart.path }}
          LOWERCASE_REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          helm push ${{ matrix.chart.name }}-*.tgz oci://ghcr.io/${LOWERCASE_REPO_OWNER}/charts
